// Code generated by goctl. DO NOT EDIT!
// Source: oburn.proto

package server

import (
	"context"

	"oburn/rpc/internal/logic"
	"oburn/rpc/internal/svc"
	"oburn/rpc/oburn"
)

type OburnServer struct {
	svcCtx *svc.ServiceContext
}

func NewOburnServer(svcCtx *svc.ServiceContext) *OburnServer {
	return &OburnServer{
		svcCtx: svcCtx,
	}
}

func (s *OburnServer) SetBurnConfig(ctx context.Context, in *oburn.SetBurnConfigRequest) (*oburn.SetBurnConfigResponse, error) {
	l := logic.NewSetBurnConfigLogic(ctx, s.svcCtx)
	return l.SetBurnConfig(in)
}

func (s *OburnServer) GetBurnConfig(ctx context.Context, in *oburn.EmptyRequest) (*oburn.GetBurnConfigResponse, error) {
	l := logic.NewGetBurnConfigLogic(ctx, s.svcCtx)
	return l.GetBurnConfig(in)
}

func (s *OburnServer) SetBurnSpeed(ctx context.Context, in *oburn.SetSpeedRequest) (*oburn.SetSpeedResponse, error) {
	l := logic.NewSetBurnSpeedLogic(ctx, s.svcCtx)
	return l.SetBurnSpeed(in)
}

func (s *OburnServer) GetBurnSpeed(ctx context.Context, in *oburn.GetSpeedRequest) (*oburn.GetSpeedResponse, error) {
	l := logic.NewGetBurnSpeedLogic(ctx, s.svcCtx)
	return l.GetBurnSpeed(in)
}

func (s *OburnServer) GetDiscInfo(ctx context.Context, in *oburn.EmptyRequest) (*oburn.GetDiscInfoResponse, error) {
	l := logic.NewGetDiscInfoLogic(ctx, s.svcCtx)
	return l.GetDiscInfo(in)
}

func (s *OburnServer) CompleteDisc(ctx context.Context, in *oburn.EmptyRequest) (*oburn.CompleteDiscResponse, error) {
	l := logic.NewCompleteDiscLogic(ctx, s.svcCtx)
	return l.CompleteDisc(in)
}

func (s *OburnServer) UnLoadDisc(ctx context.Context, in *oburn.EmptyRequest) (*oburn.UnLoadDiscResponse, error) {
	l := logic.NewUnLoadDiscLogic(ctx, s.svcCtx)
	return l.UnLoadDisc(in)
}

func (s *OburnServer) RecoverDisc(ctx context.Context, in *oburn.EmptyRequest) (*oburn.RecoverDiscResponse, error) {
	l := logic.NewRecoverDiscLogic(ctx, s.svcCtx)
	return l.RecoverDisc(in)
}

// ################################################################################
func (s *OburnServer) GetDriveInfo(ctx context.Context, in *oburn.EmptyRequest) (*oburn.DriveInfoResponse, error) {
	l := logic.NewGetDriveInfoLogic(ctx, s.svcCtx)
	return l.GetDriveInfo(in)
}

func (s *OburnServer) OpenDriveTray(ctx context.Context, in *oburn.OpenDriveTrayRequest) (*oburn.OpenDriveTrayResponse, error) {
	l := logic.NewOpenDriveTrayLogic(ctx, s.svcCtx)
	return l.OpenDriveTray(in)
}

func (s *OburnServer) CloseDriveTray(ctx context.Context, in *oburn.EmptyRequest) (*oburn.CloseDriveTrayResponse, error) {
	l := logic.NewCloseDriveTrayLogic(ctx, s.svcCtx)
	return l.CloseDriveTray(in)
}

func (s *OburnServer) GetDriveTrayStatus(ctx context.Context, in *oburn.EmptyRequest) (*oburn.GetDriveTrayStatusResponse, error) {
	l := logic.NewGetDriveTrayStatusLogic(ctx, s.svcCtx)
	return l.GetDriveTrayStatus(in)
}

func (s *OburnServer) SystemReboot(ctx context.Context, in *oburn.EmptyRequest) (*oburn.SystemRebootResponse, error) {
	l := logic.NewSystemRebootLogic(ctx, s.svcCtx)
	return l.SystemReboot(in)
}

func (s *OburnServer) SystemPoweroff(ctx context.Context, in *oburn.EmptyRequest) (*oburn.SystemPoweroffResponse, error) {
	l := logic.NewSystemPoweroffLogic(ctx, s.svcCtx)
	return l.SystemPoweroff(in)
}

func (s *OburnServer) SystemInfo(ctx context.Context, in *oburn.EmptyRequest) (*oburn.SystemInfoResponse, error) {
	l := logic.NewSystemInfoLogic(ctx, s.svcCtx)
	return l.SystemInfo(in)
}

// ################################################################################
func (s *OburnServer) PutObject(ctx context.Context, in *oburn.PutObjectRequest) (*oburn.PutObjectResponse, error) {
	l := logic.NewPutObjectLogic(ctx, s.svcCtx)
	return l.PutObject(in)
}

func (s *OburnServer) GetObject(ctx context.Context, in *oburn.GetObjectRequest) (*oburn.GetObjectResponse, error) {
	l := logic.NewGetObjectLogic(ctx, s.svcCtx)
	return l.GetObject(in)
}

func (s *OburnServer) RemoveObject(ctx context.Context, in *oburn.RemoveObjectRequest) (*oburn.RemoveObjectResponse, error) {
	l := logic.NewRemoveObjectLogic(ctx, s.svcCtx)
	return l.RemoveObject(in)
}

func (s *OburnServer) RenameObject(ctx context.Context, in *oburn.RenameObjectRequest) (*oburn.RenameObjectResponse, error) {
	l := logic.NewRenameObjectLogic(ctx, s.svcCtx)
	return l.RenameObject(in)
}

func (s *OburnServer) StatObject(ctx context.Context, in *oburn.StatObjectRequest) (*oburn.StatObjectResponse, error) {
	l := logic.NewStatObjectLogic(ctx, s.svcCtx)
	return l.StatObject(in)
}

func (s *OburnServer) ListObjects(ctx context.Context, in *oburn.ListObjectsRequest) (*oburn.ListObjectsResponse, error) {
	l := logic.NewListObjectsLogic(ctx, s.svcCtx)
	return l.ListObjects(in)
}

func (s *OburnServer) MakeBucket(ctx context.Context, in *oburn.MakeBucketRequest) (*oburn.MakeBucketResponse, error) {
	l := logic.NewMakeBucketLogic(ctx, s.svcCtx)
	return l.MakeBucket(in)
}

func (s *OburnServer) RemoveBucket(ctx context.Context, in *oburn.RemoveBucketRequest) (*oburn.RemoveBucketResponse, error) {
	l := logic.NewRemoveBucketLogic(ctx, s.svcCtx)
	return l.RemoveBucket(in)
}

func (s *OburnServer) Cancel(ctx context.Context, in *oburn.CancelRequest) (*oburn.CancelResponse, error) {
	l := logic.NewCancelLogic(ctx, s.svcCtx)
	return l.Cancel(in)
}
